[package]
name = "csgoitems"
version = "0.1.0"
authors = ["supr3meofficial <38699638+supr3meofficial@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"